export enum OnboardingStep {
  WELCOME = 'WELCOME',
  GOALS = 'GOALS',
  EXPERIENCE = 'EXPERIENCE',
  TIME_COMMITMENT = 'TIME_COMMITMENT',
  BLOCKERS = 'BLOCKERS',
  GENERATING_PLAN = 'GENERATING_PLAN',
  COMPLETED = 'COMPLETED',
}